param(
  [Parameter(Mandatory=$false)][string]$BaseUrl = "https://tm-ia.vercel.app"
)

$ErrorActionPreference = 'Stop'

$authUrl = "$BaseUrl/api/auth/google"

Write-Host "Validating OAuth redirect generated by: $authUrl" -ForegroundColor Cyan

try {
  $r = Invoke-WebRequest -UseBasicParsing -MaximumRedirection 0 $authUrl
  Write-Host "Unexpected: endpoint did not redirect (status $($r.StatusCode))." -ForegroundColor Yellow
  $r.Content
  exit 1
} catch {
  $resp = $_.Exception.Response
  if ($null -eq $resp) { throw }

  $status = [int]$resp.StatusCode
  if ($status -ne 302 -and $status -ne 301) {
    Write-Host "Expected redirect but got HTTP $status" -ForegroundColor Red
    $sr = New-Object System.IO.StreamReader($resp.GetResponseStream())
    $body = $sr.ReadToEnd()
    Write-Host $body
    exit 1
  }

  $loc = $resp.Headers["Location"]
  Write-Host "Redirect Location:" -ForegroundColor Green
  Write-Host $loc

  $u = [Uri]$loc
  $qs = [System.Web.HttpUtility]::ParseQueryString($u.Query)

  Write-Host "\nParsed params:" -ForegroundColor Cyan
  Write-Host ("client_id    = " + $qs["client_id"]) 
  Write-Host ("redirect_uri = " + $qs["redirect_uri"]) 

  if (($qs["client_id"] -match "\r|\n") -or ($loc -match "%0D%0A")) {
    Write-Host "\nWARNING: client_id contains CR/LF (will cause invalid_client)." -ForegroundColor Red
  }
}
